version: '3.8'

services:
  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=users
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "3000"  # Exposed only to other containers on the same network, not to the outside world
    networks:
      - microservice-net

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5000:5000"
    depends_on:
      - user-service
    networks:
      - microservice-net
      
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"  # Internal-only exposure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d users -h localhost -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - microservice-net

volumes:
  pgdata:

networks:
  microservice-net:
    driver: bridge

